sudo: required
language: python
python: '2.7'
install: 'pip install ansible'
before_script: 'sudo locale-gen ru_RU.UTF-8'
script:
  # Prepare tests
  - echo localhost > inventory

  # Check syntax
  - ansible-playbook --syntax-check -i inventory test.yml

  # Run
  - >
    ansible-playbook -vvv -i inventory test.yml
    --extra-vars 'deploy_user=user deploy_app_repo=https://github.com/petrikoz/itcase.deploy.git deploy_app_ver=master'

  # Check users
  - >
    id -u 'user'
    && (echo 'User test: pass' && exit 0)
    || (echo 'User test: fail' && exit 1)

  # Check files
  - ls -lA /tmp/example
  - test -d /tmp/example/run || exit 1
  - test -d /tmp/example/log || exit 1
  # configs
  - test -d /tmp/example/etc || exit 1
  - test -f /tmp/example/etc/uwsgi.ini || exit 1
  - test -f /tmp/example/etc/nginx.conf || exit 1

  # Check sources
  - test -d /tmp/example/src || exit 1
  - >
    cd /tmp/example/src;
    git remote -v | grep -q 'https://github.com/petrikoz/itcase.deploy'
    && (echo 'Src test: pass' && exit 0)
    || (echo 'Src test: fail' && exit 1)

  # Check virtualenv
  - test -d /tmp/.venvs/example || exit 1
  - test -f /tmp/.venvs/example/bin/activate || exit 1
  # virtualenvwrapper config
  - >
    cat /tmp/.venvs/example/.project | grep -q '/tmp/example/src'
    && exit 0 || exit 1
