---

- name: Make sure the deploy group are present
  group: name={{ deploy_group }}

- name: Make sure the deploy user are present
  user: name={{ deploy_user}} system=yes

- name: Ensure deploy dirs exists
  file: path={{ item }} state=directory mode=0755 owner={{ deploy_user }} group={{ deploy_group }}
  with_items:
  - '{{ deploy_dir }}'
  - '{{ deploy_etc_dir }}'
  - '{{ deploy_log_dir }}'
  - '{{ deploy_run_dir }}'
  - '{{ deploy_src_dir }}'

- name: Get source code of deploy app
  git: repo={{ deploy_app_repo }} dest={{ deploy_src_dir }} version={{ deploy_app_ver | default('HEAD') }}
  when: deploy_app_repo is defined

- name: Get venv directory
  set_fact: deploy_venv_dir={{ deploy_venv_root }}/{{ deploy_venv_name | default(deploy_app_name) }}
  when: deploy_venv_dir is not defined

- name: Ensure venv dir exists
  file: path={{ deploy_venv_dir }} state=directory mode=0755 owner={{ deploy_user }} group={{ deploy_group }}
  when: deploy_venv_dir is defined

- name: Make venv
  shell: virtualenv -p {{ deploy_venv_python }} {{ deploy_venv_options }} {{ deploy_venv_dir }}

- name: Set project home folder for venv
  lineinfile: dest={{ deploy_venv_dir }}/.project line={{ deploy_src_dir }} create=yes

- name: Make uWSGI config
  template: src=uwsgi.ini.jinja2 dest={{ deploy_etc_dir }}/uwsgi.ini

- name: Make Nginx config
  template: src=nginx.conf.jinja2 dest={{ deploy_etc_dir }}/nginx.conf
  notify:
  - nginx restart

- name: Create PostgreSQL role
  postgresql_user: name={{ deploy_pg_role_name }} password={{ deploy_pg_role_password }} login_user={{ deploy_pg_user }} login_password={{ deploy_pg_password }}

- name: Create PostgreSQL database
  postgresql_db: name={{ deploy_pg_db_name }} encoding='UTF-8' lc_collate='ru_RU.UTF-8' lc_ctype='ru_RU.UTF-8' template='template0' owner={{ deploy_pg_role_name }} login_user={{ deploy_pg_user }} login_password={{ deploy_pg_password }}

- name: Grant PostgreSQL privilegies to database
  postgresql_privs: db={{ deploy_pg_db_name }} roles={{ deploy_pg_role_name }} privs=ALL type=database login_user={{ deploy_pg_user }} login_password={{ deploy_pg_password }}
