---

- name: Make uWSGI config
  template:
    src=uwsgi.ini.jinja2
    dest={{ deploy_etc_dir }}/uwsgi.ini
    owner={{ deploy_user }}
    group={{ deploy_group }}

- set_fact: nginx_conf={{ deploy_etc_dir }}/nginx.conf

- name: Make Nginx config
  template:
    src=nginx.conf.jinja2
    dest={{ nginx_conf }}
    owner={{ deploy_user }}
    group={{ deploy_group }}

- name: Enable site in Nginx
  file: state=link force=yes src={{ nginx_conf }} dest=/etc/nginx/sites-enabled/{{ deploy_nginx_server_name }}
  become: True
  ignore_errors: True
  register: site_enabled

- name: Check Nginx config
  command: nginx -t
  register: nginx_check
  ignore_errors: True
  become: True
  when: site_enabled|succeeded

- name: Reload Nginx
  shell: echo 'Reload Nginx'
  become: True
  ignore_errors: True
  notify:
  - nginx reload
  when: nginx_check|succeeded

