---

- name: Make uWSGI config
  template: >
    src=uwsgi.ini.jinja2
    dest={{ deploy_etc_dir }}/uwsgi.ini
    owner={{ deploy_user }}
    group={{ deploy_group }}

- name: Make Nginx config
  template: >
    src=nginx.conf.jinja2
    dest={{ deploy_etc_dir }}/nginx.conf
    owner={{ deploy_user }}
    group={{ deploy_group }}
  notify:
  - nginx restart

